-- MySQL Script generated by MySQL Workbench
-- Wed Feb 24 10:26:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET
@OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET
@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET
@OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8;
USE
`mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`article`
(
    `id`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `nom`
    VARCHAR
(
    45
) NOT NULL,
    `description` VARCHAR
(
    10
) NOT NULL,
    `user_fk` INT NOT NULL,
    PRIMARY KEY
(
    `id`
),
    INDEX `user_fk_idx`
(
    `user_fk` ASC
) VISIBLE,
    CONSTRAINT `user_fk`
    FOREIGN KEY
(
    `user_fk`
)
    REFERENCES `mydb`.`user`
(
    `id`
)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comment`
(
    `id`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `contenu`
    TEXT
    NOT
    NULL,
    `article_fk`
    INT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id`
),
    INDEX `article_fk_idx`
(
    `article_fk` ASC
) VISIBLE,
    CONSTRAINT `article_fk`
    FOREIGN KEY
(
    `article_fk`
)
    REFERENCES `mydb`.`article`
(
    `id`
)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user`
(
    `` VARCHAR
(
    45
) NULL,
    `id` INT NOT NULL AUTO_INCREMENT,
    `nom` VARCHAR
(
    100
) NOT NULL,
    `prenom` VARCHAR
(
    45
) NOT NULL,
    `password` VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id`
),
    CONSTRAINT `uer_fk_idx`
    FOREIGN KEY
(
)
    REFERENCES `mydb`.`comment`
(
)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
    ENGINE = InnoDB;


SET
SQL_MODE=@OLD_SQL_MODE;
SET
FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET
UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
